<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>BSE.Tunes.WinUI.Client</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <DefaultLanguage>en</DefaultLanguage>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Controls\AlbumsCarouselView.xaml" />
    <None Remove="Controls\Carousel\Carousel.xaml" />
    <None Remove="Controls\FeaturedPlaylistView.xaml" />
    <None Remove="Controls\ItemsCarousel.xaml" />
    <None Remove="Controls\PlayerBarView.xaml" />
    <None Remove="Controls\RandomPlayerView.xaml" />
    <None Remove="Views\AlbumDetailPage.xaml" />
    <None Remove="Views\AlbumsPage.xaml" />
    <None Remove="Views\CacheSettingsPage.xaml" />
    <None Remove="Views\CreatePlaylistDialog.xaml" />
    <None Remove="Views\DeletePlaylistDialog.xaml" />
    <None Remove="Views\EndpointConfigurationPage.xaml" />
    <None Remove="Views\LoginPage.xaml" />
    <None Remove="Views\PersonalizationSettingsPage.xaml" />
    <None Remove="Views\PlaylistDetailPage.xaml" />
    <None Remove="Views\PlaylistsPage.xaml" />
    <None Remove="Views\RemoveEndpointSettingsPage.xaml" />
    <None Remove="Views\RemoveLoginSettingsPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="Controls\MenuFlyoutItem.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260209005" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageReference Include="WinUIEx" Version="2.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\ASP.Net\BSEtunes\src\BSEtunes.Contracts\BSEtunes.Contracts.csproj" />
    <ProjectReference Include="..\BSE.Tunes.Shared.Services\BSE.Tunes.Shared.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Controls\MenuFlyoutItem\MenuFlyoutItem.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <Page Update="Views\CacheSettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\DeletePlaylistDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\PlaylistDetailPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\PlaylistsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\AlbumsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\CreatePlaylistDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\AlbumDetailPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\ListView\ExtendedListViewItem.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\FeaturedPlaylistView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\RandomPlayerView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\PlayerBarView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\AlbumsCarouselView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\Carousel\Carousel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\ItemsCarousel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\FeaturedAlbumsView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\RemoveLoginSettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\RemoveEndpointSettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\PersonalizationSettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\LoginPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\EndpointConfigurationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Collections\" />
  </ItemGroup>
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>